### PR TITLE
[WIP] UserManage CRUD

### PR DESCRIPTION
**Pull request by EvanLuo42**

### CODE REVIEW

**Comment by EvanLuo42** [comment]
@iceBear67 Plz come

**Comment by iceBear67** [comment]
Do u checked if it works?

**Comment by EvanLuo42** [comment]
> Do u checked if it works?

No. If you checked the TODO, you will see the generated bean of UserGroup is not working.

**Comment by iceBear67** [comment]
Make it works and I'll merge.

**Comment by iceBear67** [comment]
And,  
It's recommended that you should `checkout a new branch` then commit your changes.

**Pull request closed without merging**
